.github/workflows/handle-contribution.yml, .github/workflows/pr-checks.yml, README.md, build-publish-alpha-package/README.md, build-publish-alpha-package/action.yml, build-push-image/README.md, build-push-release-image/README.md, build-push-release-image/action.yml, create-matrix/README.md, danger/README.md, extract-env-variables/README.md, get-workflow-sha/README.md, integration-tests/README.md, is-team-member/README.md, lint/README.md, notify-jira-about-contribution/README.md, notify-jira-about-contribution/action.yml, report-affected-packages/README.md, report-coverage/README.md, status-check/README.md, typecheck/README.md, unit-tests/README.md, upload-source-maps/README.md, yarn-install/README.md
[FX-2864](https://toptal-core.atlassian.net/browse/FX-2864)
We need to adjust GH Actions in order to make the repo public.
- Test it in a separate repo
=> [FX-2864] Update GH Actions for public repo

.github/workflows/handle-contribution.yml
Update handle contribution GH Action to properly check the contributions
- Check it in separate PR
=> Update handle contribution GH Action

.changeset/funny-geese-tickle.md, notify-jira-about-contribution/action.yml
=> chore: add missing title

.changeset/selfish-carpets-provide.md, notify-jira-about-contribution/action.yml
[FX-NNNN]
- TITLE and REPO were not injected
=> chore: access from env

.github/workflows/handle-contribution.yml
Update contribution workflow to latest
=> feat: update contribution workflow to latest

package.json, yarn.lock
In order to fix the critical alert, we need to upgrade @toptal/davinci to the latest version
- All tests must pass
=> fix: upgrade @toptal/davinci

.changeset/pink-owls-rhyme.md, .lintstagedrc.js, README.md, build-publish-alpha-package/README.md, build-publish-alpha-package/action.yml, danger/README.md, danger/action.yml, package.json, upload-source-maps/README.md, upload-source-maps/action.yml, yarn.lock
[FX-3050]
Use davinci by parts.
Fixed some READMEs to enourage people to use davinci by parts in their projects
[FX-3050]: https://toptal-core.atlassian.net/browse/FX-3050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [FX-3050] Use davinci by parts

.github/PULL_REQUEST_TEMPLATE.md
Add pr commands to the pr template
=> chore: add pr commands to pr template [skip-ci]

.eslintignore, .lintstagedrc.js, package.json, report-affected-packages/README.md, report-affected-packages/action.yml, yarn.lock
- add (required) version number to the example of `report-affected-packages`
- add lint for changeset files
- checkout branch
- generate empty changeset, add it to staged area and run lint-staged: 
`yarn changeset --empty && git add .changeset && yarn lint-staged`
<details>
<br />
</details>
=> fix: updated example with version number

depcuiser-metrics-report/README.md, depcuiser-metrics-report/action.yml
Add `envInputs` for `depcuiser-metrics-report` action
<details>
<br />
</details>
=> chore: add envInputs for depcuiser-metrics-report action

.changeset/five-bags-tickle.md, .github/workflows/pr-checks.yml, no-untracked-generated-types/README.md, no-untracked-generated-types/action.yml
[MAT-1783]
Add a check that will catch untracked changes on GQL types. It means that the branch has some types that were not generated. 
- Please check this [PR](https://github.com/toptal/client-portal/pull/5161) for testing.
<details>
<br />
</details>
[MAT-1783]: https://toptal-core.atlassian.net/browse/MAT-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAT-1783] GHA to check if there are untracked GQL types

no-untracked-generated-types/README.md
Just change reference to a proper tag in readme.
- nothing to test
- n/a Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
=> Update README.md for no-untracked-generated-types

.changeset/sharp-masks-beam.md
Add changeset for #70 
<details>
<br />
</details>
=> chore: add changeset

.changeset/big-rats-change.md, build-publish-alpha-package/README.md, build-publish-alpha-package/action.yml, build-push-image/README.md, build-push-release-image/README.md, build-push-release-image/action.yml, create-matrix/README.md, danger/README.md, depcuiser-metrics-report/README.md, deploy-storybook/README.md, deploy-storybook/action.yml, extract-env-variables/README.md, get-workflow-sha/README.md, integration-tests/README.md, is-team-member/README.md, lint/README.md, no-untracked-generated-types/README.md, notify-jira-about-contribution/README.md, notify-jira-about-contribution/action.yml, report-affected-packages/README.md, report-coverage/README.md, status-check/README.md, typecheck/README.md, unit-tests/README.md, upload-source-maps/README.md, yarn-install/README.md
=> chore: bump gh action versions

report-missing-changeset/README.md
=> fix: report-missing-changeset example

.changeset/nine-dragons-fail.md, build-push-image/action.yml
[FX-NNNN]
[Breaked GCR](https://github.com/docker/build-push-action/releases/tag/v3.3.0)
<details>
<br />
</details>
=> chore: use specific version

.changeset/mean-students-tell.md, build-push-release-image/action.yml, deploy-storybook/action.yml
[FX-NNNN]
<details>
<br />
</details>
=> chore: bump build push image versions

.changeset/healthy-items-happen.md, notify-jira-about-contribution/action.yml, notify-jira-about-contribution/notify-jira.sh
[FX-NNNN]
- escape single quotes in PR title
- Check PR in [davinci](https://github.com/toptal/davinci/pull/1868)
- Check the [contribution action](https://github.com/toptal/davinci/actions/runs/3984719070/jobs/6831844894), should succeed even when title contains single quote
<details>
<br />
</details>
=> fix: contribution action

.changeset/smart-kangaroos-deny.md, yarn-install/README.md, yarn-install/action.yml
[CI-1986](https://toptal-core.atlassian.net/browse/CI-1986)
Adding new versioning with custom cache
<details>
<br />
</details>
[CI-1986]: https://toptal-core.atlassian.net/browse/CI-1986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CI-1986 - Replace yarn cache action

.changeset/good-clouds-think.md
=> fix: wrong JSON format sent to JIRA

.changeset/changelog.config.js, .changeset/config.json, package.json
[FX-2779](https://toptal-core.atlassian.net/browse/FX-2779)
- [n/a] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
[FX-2779]: https://toptal-core.atlassian.net/browse/FX-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ci): add custom changelog config

yarn-install/README.md
Update yarn-install action README.md file.
<details>
<br />
</details>
=> chore: update yarn-install README.md

.changeset/little-cows-tap.md, .lintstagedrc.js, notify-about-build-failure/README.md, notify-about-build-failure/action.yml, notify-about-build-failure/dist/index.js, notify-about-build-failure/index.js, package.json, report-missing-changeset/index.js
[FX-4324]
This pull request adds reusable `notify-about-build-failure` action.
1. Restart the https://github.com/toptal/staff-portal/actions/runs/6460088976 job (it uses latest version of the GHA from this branch), notifications should arrive to https://toptal-core.slack.com/archives/C05VBSKHN5U and personal messages of @sashuk 
The notifications below are sent with the following settings (tested in https://github.com/toptal/staff-portal/pull/11180):
```
slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
top-team-api-key: ${{ secrets.TOP_TEAM_API_KEY }}
slack-channel-name: '#-sashuk-test-notifications-channel'
github-commit-author-name: ${{ github.event.pusher.name || 'sashuk' }}
github-action-run-url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
```
--- …
=> feat: add notify-about-build-failure GHA

.changeset/sweet-rules-try.md
=> chore: add changeset for gsm actions

.github/workflows/release.yml
[CI-3043]
The CI team is currently working on replacing the `external-proxy` with Google Identity Aware Proxy (IAP). More info [here](https://cloud.google.com/iap/docs/concepts-overview).
IAP is a Google service that allows control access to web applications running on GCP. It provides a security layer for applications by ensuring that only authenticated and authorized users/service accounts can access them. To programmatically access a resource protected by the IAP, we need to generate a JWT token and pass it alongside the request to authenticate before accessing the protected resource.
Currently, we use the `jenkins-job-trigger-action` to trigger Jenkins jobs from a GH workflow. Since this is a public action repo and to not expose our internal infrastructure implementation, we created …
=> [CI-3043] Switch to toptal/actions

yarn-install/action.yml
Disable NPM proxy while we debug why it is not working
<details>
<br />
</details>
=> Disable NPM proxy

.changeset/silly-rivers-hope.md
This pull request adds change set to properly release fix from https://github.com/toptal/davinci-github-actions/commit/6e4d78e9345c87e83660f00e4014c2cbcc1aa4e4
- change set addition, nothing to test
<details>
<br />
</details>
=> [FX-NULL] Release latest changes

.github/workflows/handle-contribution.yml
[FX-4787](https://toptal-core.atlassian.net/browse/FX-4787)
This pull request updates `davinci-github-actions` version and enables creation of contribution Jira tickets for major update `dependabot` pull request.
- All checks should pass
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
[FX-4787]: https://toptal-core.atlassian.net/browse/FX-4787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FX-4787] Update davinci-github-actions version

.changeset/beige-monkeys-type.md, gsm-secrets/action.yml
=> Bump google-github-actions/get-secretmanager-secrets to v2

.changeset/spotty-pears-hope.md, build-push-image/action.yml, yarn-install/action.yml
=> Make actions to work with runner-sets

yarn.lock
[FX-4698]
fixes https://github.com/toptal/davinci-github-actions/security/dependabot/32
<details>
<br />
</details>
[FX-4698]: https://toptal-core.atlassian.net/browse/FX-4698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FX-4698] Fix semver vulnerability

build-push-release-image/action.yml, deploy-storybook/action.yml
[No jira]
Slack thread: https://toptal-core.slack.com/archives/C03VBF0J6/p1742198646828129
- https://github.com/toptal/hire-global/actions/runs/13901677053
<details>
<br />
</details>
=> [No jira] Change build-push-release-image

.changeset/ninety-apes-smoke.md, status-check/action.yml
[TAPS-X]
<details>
<br />
</details>
=> [TAPS-X] Fix status-check action

.changeset/sour-seahorses-joke.md, .github/workflows/release.yml
[TAPS-X]
<details>
<br />
</details>
=> [TAPS-X] Fix release workflow
