toptal/davinci-github-actions

- .changeset/gorgeous-sloths-double.md
- .github/workflows/handle-contribution.yml
- notify-jira-about-contribution/action.yml
`Notify JIRA About External Contribution` GH Action does not work properly
- Create a new PR, check the result of the GH action
> Set up the proper github token

- .changeset/empty-houses-drop.md
- .github/workflows/release.yml
use the proper secret token in release GH Action
- Merge the PR and check
> Use a proper GITHUB_TOKEN in release GH Action

- build-publish-alpha-package/README.md
- build-publish-alpha-package/action.yml
No-jira
Fix a typo for command description of alpha-release
- code review is enough
- Ensure that new GH Action have a README.md file
> fix: fix typo for alpha-release action

- .changeset/warm-steaks-eat.md
- notify-jira-about-contribution/action.yml
[FX-NNNN]
- In notify jira about contribution workflow, we have: `--data '..."title": ...` We should escape/remove single quotes for the title
> chore: remove single quotes from title

- .changeset/swift-seas-happen.md
- build-push-image/README.md
- build-push-image/action.yml
In order to be able to test davinci stuff, we need to pass a custom davinci branch
- Test it in a separate repo via branch tag
> Add a custom davinci branch in build-push-image GH Action

- .changeset/short-bags-explode.md
- build-push-image/README.md
- build-push-storybook-image/README.md
- build-push-storybook-image/action.yml
[FX-2903]
Create reausable GHA for build of Storybook Docker image & push it to the cloud
- the action is used inside [topapp](https://github.com/toptal/topapp-frontend/blob/3440f09a69321297b400a096cd1454437f081b2a/.github/workflows/davinci-deploy-storybook-staging.yml#L46-L48) in [this PR](https://github.com/toptal/topapp-frontend/pull/104)
- you can rerun the [action that takes care of build&push of storybook image](https://github.com/toptal/topapp-frontend/runs/7091097470?check_suite_focus=true) and check if its being published [in the cloud](https://console.cloud.google.com/gcr/images/toptal-hub/GLOBAL/topapp-frontend-storybook?authuser=1)
[FX-2903]: https://toptal-core.atlassian.net/browse/FX-2903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
> feat: add build-push-storybook-image action

- .github/PULL_REQUEST_TEMPLATE.md
- .lintstagedrc.js
- build-push-image/README.md
- package.json
Run generation of documentation automatically on lint-staged files if any changed files is `action.yml` or `README.md`.
With this, we can simplify PR template and not require the checklist (first check is done automatically and for second check we have a workflow test)
You can test it locally:
- create a testing branch locally by running: `git fetch && git branch --no-track feat/test-branch origin/feat/generate-docs-automatically && git checkout feat/test-branch`
- run `yarn install` just to be sure you have husky prepared locally
- change any `action.yml` file, for example `build-push-image/action.yml:18` change default to `temploy`
- run `git commit -am"test: update default value"`
- check contents of `build-push-image/README.md` to see if default value for `environment` equals to …
> feat: make docs generate automatically

- .changeset/kind-mails-attend.md
- deploy-storybook/action.yml
The current name format is breaking the temploy cleaner: https://github.com/toptal/topapp-frontend/blame/master/.github/workflows/davinci-deploy-storybook-staging.yml#L77, since it expects the words before pr-number to be the repository name.
We must rename it
- Test it in topapp application
Checked here: https://github.com/toptal/topapp-frontend/pull/119
> fix: rename release name for storybook temploy

- notify-jira-about-contribution/action.yml
We used two ways to determine PR owner:
1. from action `octokit/request-action` -> outputs.user.login
2. from context `github.actor`
But lately these values didnt match, because [some flaky tickets](https://toptal-core.atlassian.net/browse/FX-2946) were created. 
In the workflow run I can only inspect the 1. value (its used as an input to action) and I can see its correct, therefore I want to use this value instead of `github.actor`. 
Advantages are:
- single source of truth for github owner
- the value is visible in the workflow run so it can be debugged later if flaky ticket is created again
- check that the value used for comparison is the same as used on line 39
> fix: using one source of truth for PR owner

- .github/PULL_REQUEST_TEMPLATE.md
- _docs/contribution/changeset-guidelines.md
Extend PR template with development checks and add changeset reminder there
I've added the section to this PR, so this is pretty much how it's going to look
> feat: add development checks with changeset to PR template

- .changeset/proud-mails-whisper.md
- yarn-install/README.md
- yarn-install/action.yml
[FX-2929]
I have a case when I need to specify a folder where I run my `yarn install`. In this case, prior to creating a temploy image I need to:
- checkout my project
- checkout davinci repo
- yarn install my project
- build my project
- create a docker image from Davinci and my project dist files
[FX-2929]: https://toptal-core.atlassian.net/browse/FX-2929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [FX-2929] Add path parameter to yarn-install action

- .changeset/ten-dryers-run.md
- yarn-install/README.md
- yarn-install/action.yml
[TDESKAPP-700]
Add the ability to run custom `yarn install` commands.
- Run the `yarn-install` action pointing to `TDESKAPP-700-install-options`
Example: https://github.com/toptal/desktop-app/actions/runs/3044433958/jobs/4904817778
<details>
<br />
</details>
[TDESKAPP-700]: https://toptal-core.atlassian.net/browse/TDESKAPP-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: allow custom install commands on yarn-install

- .changeset/cuddly-rats-report.md
- depcuiser-metrics-report/README.md
- depcuiser-metrics-report/action.yml
- depcuiser-metrics-report/dependency-cruiser-metrics-config.js
Add a new action to create a report from dependency cruiser metrics
<details>
<br />
</details>
> feat: add dependency cruiser metrics report action

- .changeset/red-waves-provide.md
- no-untracked-generated-types/action.yml
[MAT-1783]
Instead of using `path-pattern` to find only GQL types files, it was referring to some testing variable, which does not exist.
- [This check](https://github.com/toptal/client-portal/actions/runs/3385778567/jobs/5624334358)  on step "Check if ungenerated GQL types exist" -> "Run UNTRACKED_CHANGES_COUNT=0" should have this line `git status -s -u *.generated.ts ':(exclude)untracked_changes.txt' > untracked_changes.txt` with specified `path-pattern` on the check (`*.generated.ts`)
<details>
<br />
</details>
> fix: incorrect reference to path-pattern

- build-push-image/action.yml
[CI-1579]
We need to switch from Google Container Registry (GCR) to Google Artifact Registry (GAR) in order to reduce the recent [costs increase](https://cloud.google.com/storage/pricing-announce#network).
In general this is our plan:
First change the jobs that build images to push both to GCR and GAR.
Then go one by one and change the jobs to reference image at GAR.
Once we are sure we covered all, we update building jobs to remove GCR from the list. This is the first step.
- run the workflow
- check if the run is successful
- check if the image is in the artifact registry
[CI-1579]: https://toptal-core.atlassian.net/browse/CI-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: add image push to gar

- package.json
- yarn.lock
[FX-3262]
Add `lodash` to resolutions, since vorpal's inner dependencies still use vulnerable version of lodash@3
<details>
<br />
</details>
> chore(deps): add lodash to resolutions

- .changeset/warm-cheetahs-happen.md
- .lintstagedrc.js
- package.json
- report-missing-changeset/README.md
- report-missing-changeset/action.yml
- report-missing-changeset/dist/index.js
- report-missing-changeset/index.js
- report-missing-changeset/src/report-missing-changeset.js
- report-missing-changeset/src/report-missing-changeset.test.js
- yarn.lock
[FX-3300]
Add new action for monorepo that report changed packages which are not in changeset.
The difference is reported as a PR comment.
- you can check out the [Picasso PR](https://github.com/toptal/picasso/pull/3286#issuecomment-1350664508), push some changes to see how it behaves
<details>
<br />
</details>
[FX-3300]: https://toptal-core.atlassian.net/browse/FX-3300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add report-missing-dependecy action

- .lintstagedrc.js
- package.json
Add `create-matrix` action to lintstaged to run automatic bundling on change.
CONTEXT: When working with js actions, devs may forget to bundle after changing the code. 
- you can try to make some change in `create-matrix/index.js` and on commit you should see auto-bundling the code
<details>
<br />
</details>
> chore: add auto bundling

- .changeset/pretty-llamas-sort.md
- deploy-storybook/README.md
- deploy-storybook/action.yml
- yarn-install/action.yml
[GE-630]
Extending `deploy-storybook` action to support deployments for frontier-pub project, from the Growth Squad. To optimize the process, I've added a couple of options to enable using an existing Storybook package or an existing Docker image, avoiding the need of building the package/image twice. Also, an option to be able to set a custom folder name on Jenkins, since all of our jobs are on a `Frontier` folder, which does not match the repository name.
Finally, fixing `set-output` warnings from `deploy-storybook` and `yarn-install` actions, since that [will be deprecated soon](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- Changes were tested in the Jenkins jobs:
- [Temploy](https://jenkins-build.toptal.net/job/Frontier/job/f …
> [GE-630] Adjust deploy-storybook for Frontier usage

- .changeset/lucky-coats-fly.md
- deploy-storybook/README.md
- deploy-storybook/action.yml
- generate-gql-types/README.md
- generate-gql-types/action.yml
[CPT-420](https://toptal-core.atlassian.net/browse/CPT-420)
`Set up node` for deploy-storybook action and add an optional `generate  gql types` action which will be used by staff -portal in the first place.
When we comment `@toptal-bot run storybook-temploy` on a PR in staff-portal, [PR Comments](https://github.com/toptal/staff-portal/blob/884aef6e5ee0402bb0d096182138efeabfa61c28/.github/workflows/pr_job_comment.yml#L104) gets triggered and runs [Deploy Storybook to temploy](https://github.com/toptal/staff-portal/blob/46906034d031a49e89d5e04bd69909cc1619e4eb/.github/workflows/storybook_temploy_on_pr_comment.yml). And this job runs [Deploy Storybook to a particular environment](https://github.com/toptal/davinci-github-actions/blob/077a5ce65b3b1ada468957a2943bb433f1a7717b/deploy-storybook/ac …
> chore: set up node and generate types for deploy storybook

- .changeset/few-roses-hug.md
- build-push-image/action.yml
- create-matrix/README.md
[SE-2725]
Updating deprecated GitHub commands for `build-push-image`
- set-output
- actions/checkout version
- Tested using this commit as reference on this [PR](https://github.com/toptal/frontier-pub/pull/3970/commits/d90b4d3352ea1c617aab70da88559344bb87f920#diff-97cca8fb169bc3951469886bf2f73b7bcc362a6b6da11325c7a617f69a797248), fixed all warnings on our [workflow](https://github.com/toptal/frontier-pub/actions/runs/3796023309/jobs/6455726443).
<details>
<br />
</details>
[SE-2725]: https://toptal-core.atlassian.net/browse/SE-2725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SE-2725] Updating deprecated GitHub commands for build-push-image

- .changeset/shy-rocks-talk.md
- build-push-image/action.yml
- build-push-release-image/action.yml
- deploy-storybook/action.yml
- extract-env-variables/action.yml
- generate-gql-types/action.yml
[SE-2725] [GE-637]
- updating `docker/metadata-action` action version for `build-push-image package`
- updating internal packages for `build-push-release-image` and `deploy-storybook packages`
- updating `jenkins-job-trigger-action` and `actions/github-script` action version for `deploy-storybook` package
- updating `actions/github-script` action version for `extract-env-variables` package
- updating `google-github-actions/setup-gcloud` action version for `generate-gql-types` package
- Tested first commit as internal reference 
- Tested second commit as external reference https://github.com/toptal/frontier-pub/pull/3970/commits/45d956b17c9b3076ca33c87e61685afa60887104
<details>
<br />
- `@toptal-anvil ping reviewers` - Ping FX …
> [SE-2725] Fixing GHA deprecated commands for deploy-storybook package

- .changeset/famous-apricots-live.md
- build-push-release-image/action.yml
[GE-663](https://toptal-core.atlassian.net/browse/GE-663)
To fix the warning on Blackfish-Frontend project, we updated the `build-push-release-image` job..
- Tested through [this PR](https://github.com/toptal/blackfish-frontend/pull/822)
<details>
<br />
</details>
[GE-663]: https://toptal-core.atlassian.net/browse/GE-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump version build push release image

- .changeset/green-papayas-stare.md
- build-push-release-image/action.yml
- get-workflow-sha/action.yml
[GE-663](https://toptal-core.atlassian.net/browse/GE-663)
To fix the warning on Blackfish-Frontend project, we updated the `get-workflow-sha` job. Also `build-push-release-image` jobs `yarn install` is upgraded to latest version as per the suggestion on [latest PR](https://github.com/toptal/davinci-github-actions/pull/110).
- Checks should pass
- Will be tested through blackfish frontend PR
<details>
<br />
</details>
[GE-663]: https://toptal-core.atlassian.net/browse/GE-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Address deprecated commands

- .changeset/fresh-crabs-cheat.md
- get-user-slack-from-email/README.md
- get-user-slack-from-email/action.yml
- yarn-install/README.md
Add github action to retrieve slack name from user email
<details>
<br />
</details>
> feat: add action to get slack name based on email

- .changeset/silly-roses-hope.md
- build-publish-alpha-package/action.yml
- create-matrix/dist/index.js
- get-changeset-info/dist/index.js
- integration-tests/action.yml
- notify-jira-about-contribution/action.yml
- package.json
- report-missing-changeset/action.yml
- yarn-install/README.md
- yarn.lock
[FX-3708]
`set-output` and `set-state` are deprecated https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
- check [Draft PR in Picasso](https://github.com/toptal/picasso/pull/3377), there are no deprecation warnings anymore
<details>
<br />
</details>
[FX-3708]: https://toptal-core.atlassian.net/browse/FX-3708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update set-output usage

- .changeset/update.md
- danger/action.yml
[FX-2626]
Self-hosted runners may override `GITHUB_URL` variable, so requests may be performed incorectly.
This code explains how danger defined API URL: https://github.com/danger/danger-js/blob/main/source/platforms/github/GitHubAPI.ts#LL452C96-L452C118
- Use branch version in an existing GH Workflow with defined self-hosted runners
<details>
<br />
</details>
[FX-2626]: https://toptal-core.atlassian.net/browse/FX-2626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [FX-2626] set up danger env variable for self-hosted runners

- .changeset/hot-dragons-deny.md
- build-publish-alpha-package/README.md
- build-publish-alpha-package/action.yml
[FX-3737](https://toptal-core.atlassian.net/browse/FX-3737)
Added an ability to pass Davinci root folder for alpha publishing (defaults to ".")
- See if the code looks good
- See if the defaults make sense
- Test the branch action in a product using the GH action to see if it works ([Picasso test PR](https://github.com/toptal/picasso/pull/3398))
<details>
<br />
</details>
[FX-3737]: https://toptal-core.atlassian.net/browse/FX-3737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add new input to build-publish-alpha-package

- .changeset/new-icons-sleep.md
- .github/workflows/handle-contribution.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- build-push-image/action.yml
- generate-gql-types/action.yml
- get-workflow-sha/action.yml
- integration-tests/action.yml
- is-team-member/action.yml
- notify-jira-about-contribution/action.yml
- status-check/action.yml
[FX-3787](https://toptal-core.atlassian.net/browse/FX-3787)
⚠️ There will be a follow-up for changes in https://github.com/toptal/davinci-github-actions/pull/135/commits/01d5e17fb043a9ab409e4dc6c895457604ad4773
As the first step of https://toptal-core.atlassian.net/browse/FX-3787, this pull request updates all the dependencies.
Problem with https://github.com/xt0rted/pull-request-comment-branch/issues/340 (dangerous to use `@main` or `@latest`, so using a SHA as [it is safer](https://michaelheap.com/ensure-github-actions-pinned-sha/))
- No changes in behaviour are expected
- Pull request in `picasso` – https://github.com/toptal/picasso/pull/3432
- Pull request in `davinci` – https://github.com/toptal/davinci/pull/1957
<details>
<br />
List of available …
> chore: update action versions

- .changeset/selfish-bananas-brake.md
- report-affected-packages/action.yml
On of the dependencies was missed during https://github.com/toptal/davinci-github-actions/pull/135 – the `Ana06/get-changed-files` (which is in fact https://github.com/jitterbit/get-changed-files) needs to be replaced by https://github.com/masesgroup/retrieve-changed-files which is the fork but with fixes for deprecated `set-output` methods.
More infromation in https://github.com/jitterbit/get-changed-files/issues/55 and https://toptal-core.slack.com/archives/CERF5NHT3/p1678820571894699.
- Alpha package was tested in Talent Portal Frontend by comparing GHA logs (https://github.com/toptal/talent-portal-frontend/actions/runs/4418981575/jobs/7746817089#step:4:55 and https://github.com/toptal/talent-portal-frontend/actions/runs/4493260737/jobs/7904241851?pr=4733#step:4:1) …
> fix: update used action version

- .changeset/good-houses-type.md
- build-publish-alpha-package/action.yml
[FX-3832](https://toptal-core.atlassian.net/browse/FX-3832)
Alpha package release should now work without specifying `root-folder` input.
- See if the release goes through in the [example job](https://github.com/toptal/picasso/actions/runs/4533878996/jobs/7987287150?pr=3457#step:7:350) (failed for a different reason, but take a look at how the correct command is executed on the line that is linked)
<details>
<br />
</details>
[FX-3832]: https://toptal-core.atlassian.net/browse/FX-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: specify publishRootFolder only when input is provided

- get-workflow-sha/action.yml
This pull request updates the version of one of the reused GHAs (https://github.com/xt0rted/pull-request-comment-branch/blob/main/CHANGELOG.md#200---2023-03-29) and fixes the error with alpha releases.
- version bump
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
> fix: use proper version of reused GHA

- .changeset/twenty-pots-hide.md
- deploy-storybook/README.md
- deploy-storybook/action.yml
[FX-3842]
`Deploy Storybook` **GH** Action does not pass `checkout-token` to `yarn install` **GH** Action . Therefore, `yarn install` GH Action does not work properly on self-hosted runners.
- Use this branch as a version
<details>
<br />
</details>
[FX-3842]: https://toptal-core.atlassian.net/browse/FX-3842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: pass checkout-token from deploy-storybook

- .changeset/nasty-cheetahs-exercise.md
- extract-env-variables/action.yml
Support both charts - davinci-app and old chart.
Similar to https://github.com/toptal/staff-portal/blob/8151ef9feda7e12cf6c5d50d9bfe144a102df5b7/.github/scripts/readEnvVars.sh#L9
<details>
<br />
</details>
> feat: add support of davinci-app helm chart

- .changeset/tough-sheep-provide.md
- deploy-storybook/action.yml
If a project does not use `.env` files we still need to pass `ENV` to the Jenkins job. By default, it receives `ENV=null`.
Otherwise, helm tries to `--set` empty string and does not recognize RELEASE and CHART passed to the command
Example run https://jenkins-build.toptal.net/job/client-portal/job/client-portal-storybook-temploy-helm-run/8/console
<details>
<br />
</details>
> Use empty env file for storybook temploys

- .changeset/serious-hats-scream.md
- build-publish-alpha-package/action.yml
- build-push-image/action.yml
You are having problems with package [releases in Picasso](https://github.com/toptal/picasso/actions/runs/4646758303/jobs/8223366088) because of a new minimum version required for execa, which we recently bumped on [Picasso](https://github.com/toptal/picasso/commit/ba50d384f2888192d2c6d3d9eed7e896eff0435e)
- You can test it on Picasso by creating a PR using the patched workflow
<details>
<br />
</details>
> feat: depend only on the major version of node

- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
We need to update node version from 14 to 16 in GH Workflows
- Tested in others projects. As it's an infrastructure fix, it will be checked after merging
No changeset is needed. It's internal change
<details>
<br />
</details>
> chore: update node versions in github workflows

- .changeset/light-apricots-dance.md
- yarn-install/README.md
- yarn-install/action.yml
Change to use inputs.path in yarn-install action when provided.
<details>
<br />
</details>
> Use inputs.path in yarn-install action

- deploy-storybook/action.yml
[PRL-🩹]
It looks like we are not using the same [approach](https://github.com/toptal/inf-helm/blob/36a62a746fc8cd4780c35a27f7881c390ef2814f/charts/davinci-app/templates/_helpers.tpl#L16) as `helm` does.
* We need to trim name of the storybook temploy to 63 chars
* Remove `-` at the end
Here: https://github.com/toptal/staff-portal/pull/10378#issuecomment-1549746981
Domain is https://staff-portal-pr-10378-storybook-staff-portal-.toptal.rocks/ but it should be https://staff-portal-pr-10378-storybook-staff-portal.toptal.rocks/
Run: https://jenkins-build.toptal.net/view/Staff-portal/job/Staff-portal/job/staff-portal-storybook-temploy-helm-run/82/console
```
09:04:53  NAMESPACE: staff-portal-pr-10378-storybook
09:04:53  STATUS: deployed
09:04:53  REVISION: 1
09:04:53  NOTES:
09:04:53  Use the …
```
> fix: [PRL-🩹] do not use `-` at the end of the domain name and trim it to 63 chars

- .changeset/wet-brooms-tan.md
- build-push-image/action.yml
As a follow up task of migration to GAR, we need to get rid of Google Cloud registry as a registry to upload images. 
- Use branch of `build-push-image` or `build-push-release-image` GH Actions to check pushing images
Tested in https://github.com/toptal/topapp-frontend/pull/211 
<details>
<br />
</details>
> chore: remove gcr from build-push-image

- .changeset/cold-snakes-boil.md
- build-publish-alpha-package/action.yml
- build-push-image/action.yml
- deploy-storybook/action.yml
This pull request set node version to 16 everywhere as a follow-up for https://github.com/toptal/davinci-github-actions/pull/161
- All checks should pass
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
> chore: set node version to 16

- .changeset/curvy-coins-fetch.md
- yarn-install/action.yml
[TDESKAPP-1430]
Problem statement: the desktop-app project was facing issues with incompatible cache being shared.
After some investigation, I noticed that the install cache key we were using made no distinction between architectures. This PR addresses that. 
- Run the new action on machines that have the same OS but different architectures
https://github.com/toptal/desktop-app/actions/runs/5320987850/jobs/9635490741#step:6:64
https://github.com/toptal/desktop-app/actions/runs/5320987850/jobs/9635490889#step:6:64
<details>
<br />
</details>
[TDESKAPP-1430]: https://toptal-core.atlassian.net/browse/TDESKAPP-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> chore: add architecture to install cache key

- .changeset/clever-kiwis-grin.md
- upload-source-maps/README.md
- upload-source-maps/action.yml
[CRT-6175]
This PR aims to pass additional variables to upload source maps action.
Connected PRs:
- https://github.com/toptal/prospecting-assistant-extension/pull/53
- https://github.com/toptal/davinci/pull/2112 
- review https://github.com/toptal/prospecting-assistant-extension/actions/runs/5910351517/job/16031861009#step:15:67 and check that source maps are uploaded to sentry
- review https://toptal.sentry.io/issues/4404725850/?project=4505561565560832&query=release%3Amaster-3af9d00d&referrer=release-issue-stream to see that source maps are working properly
<details>
<br />
</details>
[CRT-6175]: https://toptal-core.atlassian.net/browse/CRT-6175?atlOrigin=eyJpIjoiNWRkNTlj …
> feat: [CRT-6175] pass additional variables to upload source maps action

- .changeset/hip-drinks-sip.md
- create-jira-deployment/README.md
- create-jira-deployment/action.yml
[FX-4245]
make `environment-url` input parameter optional in `create-jira-deployment` GH Action
- Use alpha version in existing GH Action
<details>
<br />
</details>
[FX-4245]: https://toptal-core.atlassian.net/browse/FX-4245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [FX-4245] make URL input parameter optional

- .changeset/stupid-grapes-sleep.md
- .github/workflows/pr-checks.yml
- create-jira-deployment/README.md
- create-jira-deployment/action.yml
[FX-4328]
make **GH** Deployment optional in `create-jira-deployment` **GH** Action. By default this feature is **disabled**
- Use branch version in Picasso PR to test
<details>
<br />
</details>
[FX-4328]: https://toptal-core.atlassian.net/browse/FX-4328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [FX-4328] make gh deployment optional

- .changeset/slimy-elephants-impress.md
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- build-publish-alpha-package/action.yml
- build-push-image/action.yml
- create-matrix/action.yml
- deploy-storybook/action.yml
- get-changeset-info/action.yml
- package.json
- report-affected-packages/action.yml
[FX-4406]
Bump node version in project to 18
- Check alpha version in Picasso (https://github.com/toptal/picasso/pull/3920)
<details>
<br />
</details>
[FX-4406]: https://toptal-core.atlassian.net/browse/FX-4406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [FX-4406] bump node version to 18

- .changeset/spicy-ears-share.md
- build-push-image/README.md
- build-push-image/action.yml
[FX-4401]
As a follow-up of https://github.com/toptal/davinci/pull/2166, `davinci-github-actions/build-push-image` action now has `docker-file` parameter changed (the old Dockerfile is deleted from `davinci-ci`)
- Configuration update, all checks should pass
<details>
<br />
</details>
[FX-4401]: https://toptal-core.atlassian.net/browse/FX-4401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: change default value of docker-file parameter

- .changeset/great-beers-hammer.md
- yarn-install/action.yml
The action accepts npm-token as a param or expects `NPM_TOKEN` env variable to exist in the job context. 
When the `NPM_TOKEN` variable exists, the job works like a charm 👍 
However, when the `NPM_TOKEN` variable doesn't exist, the `yarn cache dir` call breaks if the repository has a `.npmrc` file expecting `NPM_TOKEN` to exist
- Use this action in a workflow that doesn't have NPM_TOKEN var available (like [this](https://github.com/toptal/talent-portal-frontend/actions/workflows/library-snapshot.yml)) and see no error
| Branch | Workflow |
| --- | --- |
| https://github.com/toptal/talent-portal-frontend/compare/test-davinci-gha-224?expand=1 | https://github.com/toptal/talent-portal-frontend/actions/runs/6658308486/job/18094860780  |
The error is gone
<details>
<summary>PR …
> Fix the yarn cache dir retrieval if no NPM_TOKEN is available in env

- expose-json-outputs/README.md
- expose-json-outputs/action.yml
- expose-json-outputs/dist/index.js
- expose-json-outputs/src/index.js
- gsm-secrets/README.md
- gsm-secrets/action.yml
Those actions are alreadi in `toptal/actions`
<details>
<br />
</details>
> [CI] Add GSM actions to public repos

- .changeset/rude-goats-chew.md
- pr-conventional-to-toptal-commits/README.md
- pr-conventional-to-toptal-commits/action.yml
[FX-4409]
Add github action for renaming PRs from conventional commits to Toptal commits
- Test action on a private project
- See action run https://github.com/toptal/picasso/actions/runs/6858936980/job/18650460858?pr=3980 and event https://github.com/toptal/picasso/pull/3980#event-10949429751
<details>
<br />
</details>
[FX-4409]: https://toptal-core.atlassian.net/browse/FX-4409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4409] Add github action for renaming PRs from conventional commits to Toptal commits

- pr-conventional-to-toptal-commits/README.md
Minor housekeeping, there is no 'ubuntu-latest' label for Toptal runners (https://toptal-core.atlassian.net/wiki/spaces/CI/pages/3135570011/GHA+custom+runners+-+labels#Template-for-labels-set)
- Documentation change
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
> Fix docs in pr-conventional-to-toptal-commits

- .changeset/funny-cameras-doubt.md
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- build-publish-alpha-package/README.md
- build-publish-alpha-package/action.yml
- build-push-image/README.md
- build-push-image/action.yml
- deploy-storybook/README.md
- deploy-storybook/action.yml
- report-affected-packages/README.md
- report-affected-packages/action.yml
[FX-4432]
This pull request makes it possible to specify the version of Node.js used for 4 actions (that use the `actions/setup-node` inside).
As an example, the https://github.com/toptal/davinci-github-actions/tree/master/build-push-image action is tested in Picasso repo in https://github.com/toptal/picasso/pull/3994
- When existing Node.js version is provided
- When non-existing Node.js version is provided
<details>
<br />
</details>
[FX-4432]: https://toptal-core.atlassian.net/browse/FX-4432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add node-version parameters

- .changeset/clean-yaks-punch.md
- deploy-storybook/action.yml
[FX-4520](https://toptal-core.atlassian.net/browse/FX-4520)
Hostnames are actually truncated to 45 characters, not 63, acttording to our helm chart helpers.
<details>
<br />
</details>
[FX-4520]: https://toptal-core.atlassian.net/browse/FX-4520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4380] Fix Storybook temploy link truncation

- .changeset/chilled-turkeys-exist.md
- .github/workflows/handle-contribution.yml
- .github/workflows/release.yml
- .gitignore
[CI-2922](https://toptal-core.atlassian.net/browse/CI-2922)
CI Infrastructure is reaching the final stage of migrating all GitHub Action secrets to centralized secrets management solution: Google Secrets Manager ([here](https://toptal-core.slack.com/archives/C2W28V7L7/p1687258750273559) you can find the whole announcement). We create PRs in automatic way and the workflows are updated according to the [documentation](https://toptal-core.atlassian.net/wiki/spaces/CI/pages/3257139253/Google+Secret+Manager+-+Technical+Documentation#How-to-modify-the-GitHub-workflow-to-fetch-secrets-from-GSM). Each workflow is different, so we should test them and make adjustments if necessary.
The changes will not influence performance of the workflow execution.
- run workflow(s)
[CI-2922]: …
> [CI-2922] Update workflows to fetch secrets from GSM

- .changeset/olive-rings-help.md
- build-push-image/action.yml
- generate-gql-types/action.yml
- gsm-secrets/action.yml
[FX-3861]
This pull request updates versions of `google-github-actions/*` `and docker/*` actions.
Asked for clarifications on using the major (floating) version tags for third-party GHA in https://toptal-core.slack.com/archives/CAR6HQ2K1/p1701372038502019, any follow-ups will be addressed in separate pull requests.
- Updated actions are tested in https://github.com/toptal/picasso/pull/4038, all checks should pass
<details>
<br />
</details>
[FX-3861]: https://toptal-core.atlassian.net/browse/FX-3861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-3861] Update github actions versions

- .changeset/dry-years-breathe.md
- yarn-install/README.md
- yarn-install/action.yml
[FX-4959](https://toptal-core.atlassian.net/browse/FX-4549)
Adds option to retry yarn install
- Check https://github.com/toptal/staff-portal/pull/11712
<details>
<br />
</details>
> Add option to retry yarn-install

- .changeset/little-beans-admire.md
- create-jira-deployment/README.md
- create-jira-deployment/action.yml
- deploy-storybook/README.md
- deploy-storybook/action.yml
[CI-3043]
The CI team is currently working on replacing the external-proxy with Google Identity Aware Proxy (IAP). More info [here](https://cloud.google.com/iap/docs/concepts-overview).
IAP is a Google service that allows control access to web applications running on GCP. It provides a security layer for applications by ensuring that only authenticated and authorized users/service accounts can access them. To programmatically access a resource protected by the IAP, we need to generate a JWT token and pass it alongside the request to authenticate before accessing the protected resource.
Currently, we use the jenkins-job-trigger-action to trigger Jenkins jobs from a GH workflow. Since this is a public action repo and to not expose our internal infrastructure implementation, we created the …
> [CI-3043] Switch to trigger-jenkins-job action

- .changeset/nine-actors-camp.md
- yarn-install/README.md
- yarn-install/action.yml
The following warning was discovered after updating to latest version of davinci-github-actions in Staff Portal (https://github.com/toptal/staff-portal/actions/runs/7420502487/job/20192208624#step:9:1)
This pull request renames the parameter and makes it aligned with format of other parameters
- Parameter name change
<details>
<br />
</details>
> [FX-NULL] Rename max attempts parameter in yarn-install

- .changeset/small-icons-behave.md
- pr-conventional-to-toptal-commits/action.yml
[FX-4757]
It seems that dependabot started creating PRs with proper title format - [example](https://github.com/toptal/staff-portal/pull/11734) (check history). And when that happens the regexp is empty so the title is always empty string.
Some PRs are still opened with the old format - [example](https://github.com/toptal/topkit/pull/448)
- tested in topkit https://github.com/toptal/topkit/actions/runs/7570724233/job/20616702367?pr=448
<details>
<br />
</details>
[FX-4757]: https://toptal-core.atlassian.net/browse/FX-4757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add safe guard for title before sending to github api

- .changeset/real-clocks-provide.md
- create-matrix/action.yml
- get-changeset-info/action.yml
[FX-4769]
Bump node version for `create-matrix` and `get-changeset-info` actions.
- Use  `toptal/davinci-github-actions/create-matrix@bump-node-version-create-matrix-action` in i.e. Talent Activation repo: https://github.com/toptal/talent-activation-frontend/actions/runs/7624098507/job/20765549609?pr=2005. This failed previously due to version mismatch: https://github.com/toptal/talent-activation-frontend/actions/runs/7623751639/job/20764417446
<details>
<br />
</details>
[FX-4769]: https://toptal-core.atlassian.net/browse/FX-4769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump node version to 20 for two actions

- .changeset/cold-ducks-argue.md
- notify-about-build-failure/README.md
- notify-about-build-failure/action.yml
- notify-about-build-failure/dist/index.js
- notify-about-build-failure/index.js
[FX-4795]
We added a new feature to notify a fallback Slack group by default
- Run `toptal/davinci-github-actions/notify-about-build-failure@fx-4795-extend-notifier` with `fallback-slack-team-id` input
<details>
<br />
</details>
[FX-4795]: https://toptal-core.atlassian.net/browse/FX-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4795] Add feature to notify a fallback group

- .changeset/yellow-jokes-cheer.md
- notify-jira-about-contribution/README.md
- notify-jira-about-contribution/action.yml
[FX-4787]
This pull request enables `notify-jira-about-contribution` action to create tickets for major `dependabot` updates.
⚠️ Please note that pull request uses some temporary settings to simplify testing, they will be removed before merge
- update title of https://github.com/toptal/staff-portal/pull/11998 pull request, rerun the https://github.com/toptal/staff-portal/actions/runs/7789224900/job/21243203956 action, and observe the output of the action
or
- ✅ when pull request title is `Bump some-dependency from 2.30.0 to 3.1.0`, it is detected as major dependency update like in https://github.com/toptal/staff-portal/actions/runs/7789224900/job/21243203956#step:5:329
- ✅ when pull request title is `Bump some-dependency from 4 to 5`, it is detected as major dependency update like in …
> [FX-4787] Create tickets for major dependabot updates

- .changeset/slow-impalas-hang.md
- notify-jira-about-contribution/README.md
- notify-jira-about-contribution/action.yml
[FX-4787]
This pull request fixes the step names, so they are properly called. It also removes `dependabot-ticket-jira-label` as it was incorrectly passed to pull request labels (needs to be passed to Jira ticket, follow-up was created https://toptal-core.atlassian.net/browse/FX-4853)
Checked at https://github.com/toptal/staff-portal/pull/12036
- The https://github.com/toptal/staff-portal/actions/runs/7830088938/job/21366036170 run created ticket and assigned labels to pull request 
<details>
<br />
</details>
[FX-4787]: https://toptal-core.atlassian.net/browse/FX-4787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4787] Fix step names

- .changeset/stupid-lions-obey.md
- build-publish-alpha-package/action.yml
[CI-3174](https://toptal-core.atlassian.net/browse/CI-3174)
`build-publish-alpha-package`  [failed](https://github.com/toptal/caliber/actions/runs/7814915240/job/21317342062#step:12:37) when the workflow was switched to use custom runners.
I moved `actions/setup-node` step before the step that uses npm command. It's necessary because our custom runners doesn't have preinstalled node/npm.
- I tested setting up node here: https://github.com/toptal/inf-toolbox/actions/workflows/test-davinci-alpha-package.yml
<details>
<br />
</details>
[CI-3174]: https://toptal-core.atlassian.net/browse/CI-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> [CI] Make build-publish-alpha-package work with custom runners

- .changeset/few-swans-rush.md
- yarn-install/action.yml
[CI-3182]
Adding npm proxy variable will allow us to turn off proxy if needed (by editing organisational variables)
Github variables are set same way as github secrets and they also can be overridden per repository. In this case disabling NPM proxy could be done on org level or only for specific repositories
More about variables here https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
Run any workflow using yarn-install
<details>
<br />
</details>
[CI-3182]: https://toptal-core.atlassian.net/browse/CI-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add npm proxy variable

- .changeset/curvy-cows-promise.md
- notify-jira-about-contribution/README.md
- notify-jira-about-contribution/action.yml
- notify-jira-about-contribution/should-create-jira-issue.sh
- notify-jira-about-contribution/should-create-jira-issue.test.sh
[FX-4878]
This pull request fixes and comments the way major versions are detected for dependabot pull requests in `notify-jira-about-contribution` action. The problem was that the previous way was not working on company runners due to mismatch in `awk` implementation.
- Rerun https://github.com/toptal/davinci/actions/runs/7846448583 action that uses latest version of branch from this pull request
- Test bash script at https://www.tutorialspoint.com/execute_bash_online.php
```bash
function test {
pullRequestTitle=$1
jiraIssueAlreadyExists=false
isDraft=false
isTeamMember=false
isDependabotPullRequest=true
shouldNotifyAboutMajorDependencyUpdates=false
}
test "[FX-123] Update davinci-github-actions from 21.2 to 221"
echo "--------"
test "[FX-123] Update davinci-github-actions from 21 to …
```
> [FX-4878] Fix major version detection

- .changeset/shaggy-tigers-lie.md
- notify-jira-about-contribution/README.md
- notify-jira-about-contribution/action.yml
- notify-jira-about-contribution/notify-jira.sh
[FX-4853]
This pull request adds `major-dependency-update-jira-label` parameter to `notify-jira-about-contribution` action, so the label that is added to created Jira ticket can be configured for dependabot major updates.
https://toptal-core.atlassian.net/jira/software/c/projects/FX/settings/automate#/rule/3021227/403457150 automation was updated to take label into account
- check out https://toptal-core.atlassian.net/browse/FX-4920 (result of https://github.com/toptal/staff-portal/pull/11734), it has `ready-for-refinement` label and it was not moved in **To Do** automatically due to changes in automation
<details>
<br />
</details>
[FX-4853]: …
> [FX-4853] Add major-dependency-update-jira-label parameter

- .changeset/young-lions-smell.md
- yarn-install/action.yml
[CI-3268]
In the `yarn.lock` action, we change the yarn.lock file URLs to download the packages from npm Artifact Registry when executing `yarn install`, but after that, we need to restore the URLs to the original ones so that the workflows that have test change checks in the `yarn.lock` file after installing packages would pass.
<details>
<br />
</details>
[CI-3268]: https://toptal-core.atlassian.net/browse/CI-3268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CI-3268] Restore yarn.lock registry refs after yarn install

- .changeset/healthy-walls-judge.md
- build-push-release-image/README.md
- build-push-release-image/action.yml
[FX-4950]
To enable building docker images in multi host monorepo we need to add few more optional options.
It is being use in https://github.com/toptal/client-portal/pull/8174
<details>
<br />
</details>
[FX-4950]: https://toptal-core.atlassian.net/browse/FX-4950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4950] Make build-push-image action more reusable

- .changeset/metal-moose-cry.md
- build-push-release-image/action.yml
[FX-4996]
We need to specify a flag that highlights the Davinci Docker build
- Run this GH Action
<details>
<br />
</details>
[FX-4996]: https://toptal-core.atlassian.net/browse/FX-4996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4996] Add DAVINCI_DOCKER_BUILD env variable to build images

- .changeset/little-suits-tease.md
- yarn-install/action.yml
As you can see in the action https://github.com/toptal/client-portal/actions/runs/8602698307/job/23572835410#step:15:153 the action tries to find all yarn.lock files, including ones from the `node_modules` and `workflows` folders. Those are completely irrelevant. This creates performance issues and in some cases failure of the workflows, like in CP - https://github.com/toptal/client-portal/actions/runs/8602698307/job/23572952678
<details>
<br />
</details>
> Use single yarn.lock file to detect cache hit in yarn-install action

- .changeset/strange-garlics-fetch.md
- yarn-install/action.yml
[FX-4986]
throw an error when there are uncommitted changes in the yarn.lock
We tested that removing `--frozen-lockfile` flag has the same functionality, but updating the log file.
Tested scenarios:
- When we downgrade the library from v9 to v8 and run it with the flag, the lock file is not updated and in node modules, we have v8
- When we have in package.json `^8.0.0`, in the lock file we have `8.0.2`, and in npm, there is version `8.0.4`, after both installations, we still have `8.0.2` installed and yarn.lock is not updated. Even if we remove node_modules.
- We tested that `--frozen-lockfile` is not throwing the expected error, it is a known issue that is fixed in version 2+ and will not be backported to v1
- In the [test run](https://github.com/toptal/staff-portal/actions/runs/866146085 …
> [FX-4986] throw error when there are uncommitted changes in the yarn.lock

- .changeset/wet-ants-count.md
- yarn-install/action.yml
[FX-4986]
We forgot to add `working-directory` input in previous patch and it is making SP release to fail
<details>
<br />
</details>
[FX-4986]: https://toptal-core.atlassian.net/browse/FX-4986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4986] Run check in the working environment

- .changeset/nervous-hotels-raise.md
- build-push-image/action.yml
- yarn-install/action.yml
After migration to a new project, the name of the custom runner differs and the cache is not working properly
- Make a run on custom runner/custom runner-sets
<details>
<br />
</details>
> CI fixup yarn-install

- .changeset/tame-comics-agree.md
- notify-jira-about-contribution/README.md
- notify-jira-about-contribution/action.yml
- notify-jira-about-contribution/should-create-jira-issue.sh
- notify-jira-about-contribution/should-create-jira-issue.test.sh
This pull request is a follow-up to the problems identified in https://toptal-core.slack.com/archives/GG3F4AS4T/p1717170652381949 – the pull request adds ability not to create tickets for major dependency update if they match a regexp (the default value is `/@toptal/`).
- Please follow unit test instructions in https://github.com/toptal/davinci-github-actions/blob/FX-NULL-improve-contribution-notification/notify-jira-about-contribution/should-create-jira-issue.test.sh#L1
<details>
<br />
</details>
> [Fx-NULL] Add ability to ignore certain major update packages

- yarn-install/action.yml
[GE-1005]
We are updating the `yarn-install` workflow as it's calling some outdated actions that use Node 16, which is causing some deprecation warnings as it has already reached it's EOL.
- You can see the workflow that uses `yarn-install` passing [here](https://github.com/toptal/blackfish/actions/runs/9653485728/job/26626333348?pr=11166) with no deprecation warnings. For reference, you can compare against [this master run](https://github.com/toptal/blackfish/actions/runs/9650763863), which shows the deprecation warnings
<details>
<br />
</details>
[GE-1005]: https://toptal-core.atlassian.net/browse/GE-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> [GE-1005] Fix node deprecation warnings in Yarn Install action

- .changeset/wet-rivers-sparkle.md
- build-push-image/action.yml
- extract-env-variables/action.yml
[GE-1029]
We are updating the `ssh-agent` action version on the `build-push-image` action, as it's using Node 12
- You can see the action working, without the deprecation warning, [in this run](https://github.com/toptal/frontier-pub/actions/runs/9714066603/job/26812388150?pr=7005)
<details>
<br />
</details>
[GE-1029]: https://toptal-core.atlassian.net/browse/GE-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GE-1029] Fix GHA Node deprecation warnings in build-push-image action

- package.json
- yarn.lock
[FX-4698]
fixes https://github.com/toptal/davinci-github-actions/security/dependabot/45
the vulnerable version of `axios` was used in the old segment library, so we have to update `@toptal/davinci-syntax` to get rid of Axios completely. The syntax package is used only for prettier config and it is only a dev dependency, everything should work fine.
------
fixes https://github.com/toptal/davinci-github-actions/security/dependabot/39
<details>
<br />
</details>
[FX-4698]: https://toptal-core.atlassian.net/browse/FX-4698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FX-4698] Update @toptal/davinci-syntax to remove axios

- package.json
- yarn.lock
[FX-4698]
Fixes
- https://github.com/toptal/davinci-github-actions/security/dependabot/19
- https://github.com/toptal/davinci-github-actions/security/dependabot/25
- https://github.com/toptal/davinci-github-actions/security/dependabot/21
`jsonwebtoken` is used by happo in `@toptal/davinci-qa`, fixed after update
----
Fixes https://github.com/toptal/davinci-github-actions/security/dependabot/37
Cypress is not part of davinci-qa anymore. It is expected to be installed on user side when needed.
----
Fixes https://github.com/toptal/davinci-github-actions/security/dependabot/31
<details>
<br />
</details>
[FX-4698]: …
> [FX-4698] Update@toptal/davinci-qa

- .changeset/sweet-pigs-rhyme.md
- automerge-release-pr/README.md
- automerge-release-pr/action.yml
During one of Retro meetings we decided that we want to automerge major version packages pull requests in Frontend Experience products (minor and patch versions are already automerged).
While changing the logic I noticed that there is quite some duplication in three repos
- https://github.com/toptal/davinci/blob/master/.github/workflows/automerge-release.yaml
- https://github.com/toptal/topkit/blob/master/.github/workflows/automerge-release.yaml
- https://github.com/toptal/picasso/blob/master/.github/workflows/automerge-release.yaml
This pull request extracts automerge logic into composite action, so there is a single source of truth (DRY). If we want to change the logic later, it can be changed only in one place.
The plan
- merge this pull request
- reuse action in Topkit
- make sure …
> [FX-NULL] Add automerge composite action

- .github/workflows/release.yml
[OPS-22](https://toptal-core.atlassian.net/browse/OPS-22)
We are decommissining jenkins-build instance so we are migrating all the jobs to jenkins.toptal.net
<details>
<br />
</details>
[OPS-22]: https://toptal-core.atlassian.net/browse/OPS-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OPS-22] Remove jenkins-build from code

- .changeset/long-poems-work.md
- build-push-image/README.md
- build-push-image/action.yml
Add `gh-runners-driver-opts` input in build-push action.
We can use a custom image to avou DockerHub Rate limit errors like: 
`Fix Error: ERROR: Error response from daemon: No such image: moby/buildkit:buildx-stable-1` / `ERROR: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`
- Action is green in a workflow using it
<details>
<br />
</details>
> [FX-NULL] Add gh-runners-driver-opts option

- .changeset/nervous-oranges-obey.md
- build-push-release-image/README.md
- build-push-release-image/action.yml
Similar to https://github.com/toptal/davinci-github-actions/pull/356, we want to pass options to `buildx` in `build-push-release-image` job.
<details>
<br />
</details>
> [FX-NULL] Pass parameter to build-push-image

- .changeset/nice-seahorses-buy.md
- yarn-install/action.yml
Fix for custom usage of path parameter. If path input parameter is used - use `yarn.lock` file from that path to generate cache hash.
The modified GHA is tested in https://github.com/toptal/client-portal/actions/runs/12235817455 (https://github.com/toptal/client-portal/pull/10141)
<details>
<br />
</details>
> Fix usage of custom path in yarn-install

- .changeset/hip-coins-bathe.md
- yarn-install/action.yml
[TAPS-425]
This PR aims to improve `yarn-install` action for scenario when there is no occurrence of `registry.npmjs.org` inside `yarn.lock`. We have this case in screening-wizard-frontend.
- Review testing run: https://github.com/toptal/platform/actions/runs/12632044990 (PR with inlining `yarn-install` into platform to test changes: https://github.com/toptal/platform/pull/80504/files)
<details>
<br />
</details>
[TAPS-425]: https://toptal-core.atlassian.net/browse/TAPS-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TAPS-425] Improve yarn-install action

- .changeset/fuzzy-bees-applaud.md
- yarn-install/action.yml
I have faced a problem integrating yarn-install action into [tracker-front](https://github.com/toptal/tracker-front) where we have yarn.lock that gets all packages through registry.yarnpkg.com, so not a single mention of registry.npmjs.com is there, and this leads to `Change registry in yarn.lock file to npm Artifact Registry` step failing with an error (e.g. https://github.com/toptal/tracker-front/actions/runs/12527127099/job/34940394300?pr=3264)
Initially tried to hunt down and fix this specific problem, but debugging this quite complex bash script came to conclusion it's kind of overengineered and we can achieve the same behavior with much more simple and even more performant implementation. Thus this is my suggestion
The idea if existing implementation is that after running yarn …
> Simplify the way yarn-install action ensures yarn.lock stays unchanged after `yarn install`

- .github/workflows/release.yml
[TAPS-436]
<details>
<br />
</details>
[TAPS-436]: https://toptal-core.atlassian.net/browse/TAPS-436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TAPS-436] Move notifications to new channel

- .github/workflows/pr-checks.yml
Fixes failing `Trufflehog Scan` check:
-  `Trufflehog Scan` should pass on this PR
- [n/a] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
> Bump edplato/trufflehog-actions-scan to v0.9m-beta

- .changeset/polite-balloons-melt.md
- create-matrix/README.md
- generate-gql-types/action.yml
- integration-tests/action.yml
- report-missing-changeset/README.md
Started to see issues like this in some repos:
[link to the failed workflow](https://github.com/toptal/staff-portal/actions/runs/12811334688/job/35725271461)
So updating usage of github actions from v3 to v4
<details>
<br />
</details>
> Update github actions from v3 to v4

- .changeset/perfect-cars-relate.md
- yarn-install/action.yml
[TAPS-507]
This PR aims to fix `yarn-install` action which changes the `.npmrc` file, example of the Graphql schema update PR which contains unexpected `.npmrc` file change: https://github.com/toptal/talent-portal-frontend/pull/6676
- review the run which contains the fix from this PR: https://github.com/toptal/talent-portal-frontend/actions/runs/13131796175/job/36638348074
- review the Schema Update PR which was created with the with from this PR: https://github.com/toptal/talent-portal-frontend/pull/6684
<details>
<br />
</details>
[TAPS-507]: https://toptal-core.atlassian.net/browse/TAPS-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> [TAPS-507 Fix yarn-install action

- .changeset/clean-moons-look.md
- yarn-install/action.yml
[TAPS-507]
This PR fixes error in https://github.com/toptal/talent-portal-frontend/actions/runs/13133866860/job/36644938912#step:9:398
```bash
fatal: detected dubious ownership in repository at '/__w/talent-portal-frontend/talent-portal-frontend'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/talent-portal-frontend/talent-portal-frontend
Error: Process completed with exit code 128.
```
- Green CI in following repositories (where we used `yarn-install` from this PR):
- https://github.com/toptal/screening-wizard-frontend/pull/1754, run: https://github.com/toptal/screening-wizard-frontend/actions/runs/13153753165?pr=1754
- https://github.com/toptal/client-portal/pull/10307, run: https://github.com/toptal/client-portal/actions/runs/13153722806?pr=10 …
> [TAPS-507] Use `mv` and `cp` commands to restore original `.npmrc` file instead of `git`

- .changeset/gentle-llamas-deliver.md
- build-push-image/README.md
- gsm-secrets/action.yml
Infra is moving to `wif` and we need to upgrade our gsm-secrets to expose access token 
https://github.com/toptal/actions/blob/main/gsm-secrets/action.yml
<details>
<br />
</details>
> [FF-] Expose access_token
